### ISSUE TITLE
can't use zoom scroll or viewport

### ISSUE THREAD

**Issue by icryrainix** [utelle/wxchartdir#1]
Under mac os, compiled successfully, but unable to run with functions: realtimeviewport, zoom, track etc. the error message is: CGContextScaleCTM: invalid context 0x0.

**Comment by utelle** [comment]
Unfortunately I don't have access to a Mac OSX computer. Therefore I can't test this myself.

As far as I can tell neither the wxChartDir wrapper nor the ChartDirector library calls function CGContextScaleCTM directly. So maybe some underlying wxWidgets method throws this error message.

Does the error show up in the sample applications coming with wxChartDir? Or in your own application? If sample applications are affected: do all sample applications fail? Or just some? In the latter case: which ones?

Can you build wxChartDir in debug mode? It would be helpful to see a call stack when the error occurs, so that we can track down where exactly the error occurs.

**Comment by icryrainix** [comment]
Thank you ver much for your quick response.

I tested the samples provided under wxdemo, and found those static charts, it is ok, but dynamic chart, including draw track line, zoom and scroll, real time etc, the error will occurred. the following message is backtrace of drawtrackline:
<_Z16wxOSXDrawNSImageP9CGContextPK6CGRectP7NSImage+43>
   <_ZN24wxMacCoreGraphicsContext10DrawBitmapERK8wxBitmapdddd+116>
    <_ZN10wxGCDCImpl12DoDrawBitmapERK8wxBitmapiib+1216>
     <_ZN4wxDC10DrawBitmapERK8wxBitmapiib+84>
      <_ZN13wxChartViewer6RenderER4wxDCP9BaseChart+232>
       <_ZN13wxChartViewer8PaintNowEP9BaseChart+54>
        <_ZN13wxChartViewer17CommitUpdateChartEv+147>
         <_ZN13wxChartViewer13updateDisplayEv+42>
          <_ZN13wxChartViewer8setChartEP9BaseChart+149>
           <_ZN12TrackFinance9DrawChartEP13wxChartViewer+1515>
            <_ZN12TrackFinance14CreateControlsEv+339>
             <_ZN12TrackFinance6CreateEP8wxWindowiRK8wxStringRK7wxPointRK6wxSizel+301>
              <_ZN12TrackFinanceC2EP8wxWindowiRK8wxStringRK7wxPointRK6wxSizel+120>
               <_ZN12TrackFinanceC1EP8wxWindowiRK8wxStringRK7wxPointRK6wxSizel+75>
                <_ZN15TrackFinanceApp6OnInitEv+459>
                 <_ZN5wxApp10CallOnInitEv+357>
                  <_Z7wxEntryRiPPw+184>
                   <_Z7wxEntryRiPPc+60>
                    <main+38>                     <start+1>

**Comment by utelle** [comment]
Looking at the call stack I get the impression that method PaintNow gets called too early, when the wxWidgets drawing context is not yet ready to accept drawing commands. Interestingly this doesn't happen under Windows or Linux.

I have to further investigate the issue. I'll try to come up with an attempt to fix it within the next few days.

**Comment by utelle** [comment]
There might be an issue with wxWidgets itself. In wxWidgets version 3.1.2 method `wxMacCoreGraphicsContext::DrawBitmap` was changed to directly use `NSImage` drawing using function `wxOSXDrawNSImage`. A context variable is passed as the first parameter of this function, but it is not checked whether this context variable is properly initialized (in contrast to other methods which call `EnsureIsValid` first, before using the context variable).

**Comment by utelle** [comment]
I reported the potential problem in wxWidgets to the wxWidgets developers, and they applied a fix (see
https://github.com/wxWidgets/wxWidgets/commit/099de4ecab8fd94baf74c06530982653fc46ad16).

Please test with this adjusted wxWidgets version to check whether this fixes your issue with **wxChartDir**, too. Please report back your findings. Thanks

**Comment by icryrainix** [comment]
Great, it is OK now. Thanks.
