### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by rodingbao** [utelle/wxchartdir#15]
pls guide how to compile. 

I  command "mingw32-make -f makefile config=release_dll_win64" in windows 11.
the error message show as belowing. it seems that cant find the lib of wxWidgets, but I had set up Environment variables “WXWIN”  for the wxWidgets root path. .

D:\wxchartdir\wxdemo\build>mingw32-make  wxchartviewer  config=release_dll_win64
"==== Building wxchartviewer (release_dll_win64) ===="
Creating obj/gcc/Win64/Release_DLL/wxchartviewer
wxchartviewer_version.rc
wxchartviewer.cpp
Creating ../lib/gcc_x64_dll
Linking wxchartviewer
C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxmsw31u_core
C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxbase31u_xml
C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxbase31u
C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxjpeg
C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxpng
C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxzlib
C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxtiff
C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxexpat
C:/Program Files (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwxregexu
collect2.exe: error: ld returned 1 exit status
wxchartviewer.make:193: recipe for target '../lib/gcc_x64_dll/libwxchartdir.dll' failed
mingw32-make[1]: *** [../lib/gcc_x64_dll/libwxchartdir.dll] Error 1
Makefile:131: recipe for target 'wxchartviewer' failed
mingw32-make: *** [wxchartviewer] Error 2

**Comment by utelle** [comment]
> I command "mingw32-make -f makefile config=release_dll_win64" in windows 11.
> the error message show as belowing. it seems that cant find the lib of wxWidgets, but I had set up Environment variables “WXWIN” for the wxWidgets root path.

When compiling with the gcc compiler using `mingw32-make` you will have to check (and modify, if necessary) the build configuration file `config.gcc` in the `build` subdirectory of _wxChartDir_.

What exactly you will have to adjust, depends on how you built the wxWidgets libraries. Did you compile wxWidgets yourself? Or do you use precompiled binaries?

Please check your wxWidgets installation: the link libraries and the DLLs should reside in a subdirectory of directory `$(WXWIN)/lib` - the name of the subdirectory will be something like `gcc[XYZ][_x64]_dll` where **[XYZ]** is typically the gcc compiler version, but could be empty, if you built wxWidgets yourself. The architecture part **[_x64]** could also be empty, if you built wxWidgets yourself.

Most likely, you will have to adjust at least the compiler prefix

```Make
# Compiler prefix
wxCompilerPrefix ?= gcc810
```

`gcc810` is the default value in `config.gcc`. If you built wxWidgets yourself, the prefix is probably just `gcc`.

Unfortunately, the official wxWidgets make files do not set the architecture. That is, the wxWidgets library directory is probably just `lib/gcc_dll` for the 64-bit build.

To overcome this obstacle, you will have to change in `config.gcc` all occurences of 
```Make
wxArchSuffix = _x64
```

to
```Make
wxArchSuffix =
```

**Comment by rodingbao** [comment]
it works, thanks.
