### ISSUE TITLE
Getting a chart to fill a panel?

### ISSUE THREAD

**Issue by tonyvsuk** [utelle/wxchartdir#7]
Hello,

I'm really struggling to get a chart to fill the parent panel. I've tried calling setSize, but this does not seem to do anything. Also tried refresh etc, nothing I do makes the chart resize.

Can anyone help?

Thanks in advance,

Tony.

**Comment by utelle** [comment]
Yes, because you have to inform _ChartDirector_ about the changed dimensions of the chart area, so that later on method `makeChart` can retrieve the chart bitmap in the requested size.
